### ISSUE TITLE
Editor with Basic Types

### ISSUE THREAD

**Issue by TURX** [TexteaInc/funix#2]
Now the editor only supports type as `helperText` and everything is in `string`. The frontend should support basic types supported by the backend.

**Comment by Yazawazi** [comment]
Support: `boolean`, `int`, `float`, `list`, `range`, str, `dict`
Not support: `complex`, `tuple`, `bytearray`, `memoryview`, `set`, `frozenset`
Special: `bytes` (See `from funix.hint import Bytes[Widget]`)

I will close this issue as we do not have support for the remaining types of ideas for now.
