### ISSUE TITLE
Proxy on frontend for requests to backend

### ISSUE THREAD

**Issue by TURX** [TexteaInc/funix#60]
Some services (e.g., Google App Engine, Heroku) only allow one port to be exposed for a service. In this case, we need to set up a proxy in [the entry point](https://github.com/TexteaInc/funix/blob/main/frontend/src/index.tsx) under the `/api` route, for user to access backend through frontend without exposing the backend port.

Here are some links which might be useful:
- https://stackoverflow.com/questions/54393325/proxy-api-request-using-react-router
- https://www.npmjs.com/package/http-proxy-middleware

**Comment by Yazawazi** [comment]
The frontend and backend share the same port now, no need to worry about naming, just note the function names like `static`, `config` and `files`. `static`, `config` are introduced by the frontend service: static resources and backend configuration (use the local frontend to connect to others' backend services); the `files` is introduced by the backend service: the local file system. I'm considering introducing a decorator parameter that can rename function names to solve that naming problem.

https://github.com/TexteaInc/funix/commit/84920e037d0a877875e77e6e18f418cf8870278d
