### ISSUE TITLE
IP Issue on cloud deployment 

### ISSUE THREAD

**Issue by forrestbao** [TexteaInc/funix#62]
I just tried to set up the demo on Google Compute Engine. But I ran into an issue related to the internal and external IP of an cloud VM. 

**Observations**

I started my Funix server using 
```
python3 -m funix examples_better -H 10.128.0.2
```
where 10.128.0.2 is the internal IP of the instance. 

However, the Funix frontend in my browser (on my local computer) cannot access this IP. 

I managed to get it to work by changing the backend IP in the settings in the Funix app in the browser to the external IP of the server. But this is very not out-of-the-box. We can expect common Joes to change this setting. 

**Proposed change**

Add another option to Funix to configure the external IP and pass this to the browser.

**Comment by Yazawazi** [comment]
Fixed in `0.3.7`
