### ISSUE TITLE
Matplotlib figures does not display in first run

### ISSUE THREAD

**Issue by forrestbao** [TexteaInc/funix#71]
To repeat, use this example: https://github.com/TexteaInc/funix/blob/main/examples/slider_table_plot.py

The expected matplotlib figure does not display when the Run button is clicked for the first time. It is only displayed if Run button is clicked again. Future clicks of Run button generate new plots as expected.

**Comment by Yazawazi** [comment]
https://github.com/TexteaInc/funix/blob/8ac9a75bd455233074cf909452c29dee3edba6b6/backend/funix/decorator/__init__.py#L1035-L1047

Fixed, please test again
